name: ServerConnector
version: '${project.version}'
main: de.tobias.serverconnector.ServerConnector
api-version: '1.20'
commands:
  shutdown:
    description: Schaltet den Server aus.
    usage: /shutdown
permissions:
  admin.action.shutdown:
    default: op
    description: Permission to shutdown the server