name: spawnProtect
version: '${project.version}'
main: de.tobias.spawnprotect.SpawnProtect
api-version: 1.19
authors: [Tobias Auer]
description: Protects Spawn from griefing and mob spwaning
website: https://www.github.com/tobias-auer
