name: PermissionSystem
version: '${project.version}'
main: de.tobias.permissionsystem.PermissionSystem
api-version: 1.19
commands:
  perm:
    description: Manage the permisssions for all player
    usage: /perm <add|remove|list> <player> <permission>
    permission: admin.manage.playerpermission

permissions:
  admin.manage.playerpermission:
    default: op
    description: Permission to give other player permissions