# {0} = Reason
# {1} = Start time
# {2} = End time
# {3} = Administrator
ban-message: |
  §4Du wurdest vom Servernetzwerk ausgeschlossen!
  
  
  
  §5Grund: §r{0}
  
  §6Zuständiger Administrator: §r{3}
  
  §dGebannt seit: §r{1}
  §dGebannt bis: §r{2}
  
  
  §2Entbannungsantrag: §fsurvival0.duckdns.org/unban

welcomeback-message1: §2Willkommen zurück!
welcomeback-message2: §4! §rBitte halte dich ab jetzt an die Regeln §4!

