name: EasyBan
version: '${project.version}'
main: de.tobias.easyban.EasyBan
api-version: 1.19
commands:
  ban:
    description: ban players
    tab-completer: de.tobias.easyban.EasyBanCommandListener
    usage: ban <player> <reason> <minutes> <hours> <days> <months>
    permission: admin.ban
  unban:
    description: unban players
    tab-completer: de.tobias.easyban.EasyBanCommandListener
    usage: unban <player>
    permission: admin.ban


permissions:
  admin.ban:
    default: op
    description: Permission to ban and unban other players
